#!/usr/bin/env python3
"""Generate data.js from the JSON block (section 11) of the blocking report.

Usage: python3 tools/build_data.py [data/sprint-2-blocking-report.md] [data.js]

Owners and reviewers are dropped on purpose: assignments happen on the board.
Only structural edges are kept (hard, file, soft, decision). The chronological
ones (owner-queue, not-before, stretch-gate) depend on owners or the schedule,
so the board ignores them.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "data" / "sprint-2-blocking-report.md"
OUT = Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "data.js"

KEPT_EDGE_KINDS = {"hard", "file", "soft", "decision"}

# Contracts and process items are not listed as story children in the report.
# Place each contract right before the task it starts (section 7.2), and give
# the process items their own row.
EXTRA_CHILDREN = {"C5": "V4.2", "C6": "E3.1", "C7": "E4.1"}
PROC_ROW = {"id": "PROC", "title": "Process (no user story)", "prio": "must",
            "children": ["DEC-1", "DEC-2", "DEC-3", "DEC-4", "DEC-5", "DEC-6", "HK-1", "M1"]}

# Order of the rows, as in section 7.2 of the report.
STORY_ORDER = ["G2", "G3", "V3", "V4", "E3", "Q", "N", "V1", "T", "E4", "E5", "V9", "V10", "E6", "PROC"]


def main():
    md = SRC.read_text(encoding="utf-8")
    match = re.search(r"## 11\..*?```json\n(.*?)\n```", md, re.S)
    if not match:
        sys.exit("No JSON block found in section 11")
    plan = json.loads(match.group(1))

    tasks = {t["id"]: t for t in plan["tasks"]}
    stories = {t["id"]: t for t in plan["tasks"] if t["kind"] == "story"}
    stories["PROC"] = PROC_ROW

    rows = []
    for sid in STORY_ORDER:
        s = stories[sid]
        children = list(s["children"])
        for contract, before in EXTRA_CHILDREN.items():
            if before in children:
                children.insert(children.index(before), contract)
        rows.append({"id": sid, "title": s["title"], "prio": s.get("prio", "must"), "children": children})

    placed = [c for r in rows for c in r["children"]]
    non_story = [t for t in tasks if tasks[t]["kind"] != "story"]
    missing = sorted(set(non_story) - set(placed))
    dupes = sorted({c for c in placed if placed.count(c) > 1})
    if missing or dupes:
        sys.exit(f"Row layout broken. missing={missing} duplicated={dupes}")

    out_tasks = {}
    for tid in placed:
        t = tasks[tid]
        out_tasks[tid] = {
            "title": t["title"],
            "kind": t["kind"],
            "alias": t.get("alias"),
            "prio": t.get("prio", "must"),
            "size": t.get("size"),
            "window": [t.get("windowStartDay"), t.get("windowEndDay")],
            "github": t.get("github"),
            "existing": t.get("existingWork"),
            "files": t.get("files", []),
        }

    edges = []
    for e in plan["edges"]:
        if e["kind"] not in KEPT_EDGE_KINDS:
            continue
        if e["from"] not in out_tasks or e["to"] not in out_tasks:
            sys.exit(f"Edge points at an unknown task: {e}")
        edges.append({"from": e["from"], "to": e["to"], "kind": e["kind"],
                      "blocks": e["blocks"], "reason": e.get("reason", "")})

    payload = {"rows": rows, "tasks": out_tasks, "edges": edges}
    OUT.write_text(
        "// Generated by tools/build_data.py from data/sprint-2-blocking-report.md. Do not edit by hand.\n"
        "export const PLAN = " + json.dumps(payload, indent=1, ensure_ascii=False) + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT}: {len(rows)} rows, {len(out_tasks)} tasks, {len(edges)} edges")


if __name__ == "__main__":
    main()
